// <auto-generated />
namespace Britespokes.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddHotelInformationToTourMeta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHotelInformationToTourMeta));
        
        string IMigrationMetadata.Id
        {
            get { return "201308181913509_AddHotelInformationToTourMeta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
