// <auto-generated />
namespace Britespokes.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddExperiences : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExperiences));
        
        string IMigrationMetadata.Id
        {
            get { return "201308201607380_AddExperiences"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
