// <auto-generated />
namespace Britespokes.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddConfirmationNumberToTraveler : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConfirmationNumberToTraveler));
        
        string IMigrationMetadata.Id
        {
            get { return "201306041640332_AddConfirmationNumberToTraveler"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
