// <auto-generated />
namespace Britespokes.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TourMetaPriceIncludesShouldNotBeRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TourMetaPriceIncludesShouldNotBeRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201308192047122_TourMetaPriceIncludesShouldNotBeRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
