using System.Data.Entity.Migrations;
using System.Data.Entity.Validation;
using System.Diagnostics;
using Britespokes.Core.Domain;

namespace Britespokes.Data.Migrations
{
  internal class GeoSeeder
  {
    public static void Seed(EfDbContext context)
    {
      try
      {
        context.Countries.AddOrUpdate(c => c.Iso, Countries());
        context.SaveChanges();

        context.States.AddOrUpdate(c => c.Abbreviation, States());
        context.SaveChanges();
      }
      catch (DbEntityValidationException dbex)
      {
        foreach (var dbEntityValidationResult in dbex.EntityValidationErrors)
          foreach (var dbValidationError in dbEntityValidationResult.ValidationErrors)
            Debug.WriteLine("{0}: {1}", dbValidationError.PropertyName, dbValidationError.ErrorMessage);
        throw;
      }
    }

    private static Country[] Countries()
    {
      var countries = new[]
      {
        new Country { Iso = "AF", Name = "AFGHANISTAN", PrintableName = "Afghanistan", Iso3 = "AFG", CountryCode = 4 },
        new Country { Iso = "AL", Name = "ALBANIA", PrintableName = "Albania", Iso3 = "ALB", CountryCode = 8 },
        new Country { Iso = "DZ", Name = "ALGERIA", PrintableName = "Algeria", Iso3 = "DZA", CountryCode = 12 },
        new Country { Iso = "AS", Name = "AMERICAN SAMOA", PrintableName = "American Samoa", Iso3 = "ASM", CountryCode = 16 },
        new Country { Iso = "AD", Name = "ANDORRA", PrintableName = "Andorra", Iso3 = "AND", CountryCode = 20 },
        new Country { Iso = "AO", Name = "ANGOLA", PrintableName = "Angola", Iso3 = "AGO", CountryCode = 24 },
        new Country { Iso = "AI", Name = "ANGUILLA", PrintableName = "Anguilla", Iso3 = "AIA", CountryCode = 660 },
        new Country { Iso = "AQ", Name = "ANTARCTICA", PrintableName = "Antarctica", Iso3 = null, CountryCode = null },
        new Country { Iso = "AG", Name = "ANTIGUA AND BARBUDA", PrintableName = "Antigua and Barbuda", Iso3 = "ATG", CountryCode = 28 },
        new Country { Iso = "AR", Name = "ARGENTINA", PrintableName = "Argentina", Iso3 = "ARG", CountryCode = 32 },
        new Country { Iso = "AM", Name = "ARMENIA", PrintableName = "Armenia", Iso3 = "ARM", CountryCode = 51 },
        new Country { Iso = "AW", Name = "ARUBA", PrintableName = "Aruba", Iso3 = "ABW", CountryCode = 533 },
        new Country { Iso = "AU", Name = "AUSTRALIA", PrintableName = "Australia", Iso3 = "AUS", CountryCode = 36 },
        new Country { Iso = "AT", Name = "AUSTRIA", PrintableName = "Austria", Iso3 = "AUT", CountryCode = 40 },
        new Country { Iso = "AZ", Name = "AZERBAIJAN", PrintableName = "Azerbaijan", Iso3 = "AZE", CountryCode = 31 },
        new Country { Iso = "BS", Name = "BAHAMAS", PrintableName = "Bahamas", Iso3 = "BHS", CountryCode = 44 },
        new Country { Iso = "BH", Name = "BAHRAIN", PrintableName = "Bahrain", Iso3 = "BHR", CountryCode = 48 },
        new Country { Iso = "BD", Name = "BANGLADESH", PrintableName = "Bangladesh", Iso3 = "BGD", CountryCode = 50 },
        new Country { Iso = "BB", Name = "BARBADOS", PrintableName = "Barbados", Iso3 = "BRB", CountryCode = 52 },
        new Country { Iso = "BY", Name = "BELARUS", PrintableName = "Belarus", Iso3 = "BLR", CountryCode = 112 },
        new Country { Iso = "BE", Name = "BELGIUM", PrintableName = "Belgium", Iso3 = "BEL", CountryCode = 56 },
        new Country { Iso = "BZ", Name = "BELIZE", PrintableName = "Belize", Iso3 = "BLZ", CountryCode = 84 },
        new Country { Iso = "BJ", Name = "BENIN", PrintableName = "Benin", Iso3 = "BEN", CountryCode = 204 },
        new Country { Iso = "BM", Name = "BERMUDA", PrintableName = "Bermuda", Iso3 = "BMU", CountryCode = 60 },
        new Country { Iso = "BT", Name = "BHUTAN", PrintableName = "Bhutan", Iso3 = "BTN", CountryCode = 64 },
        new Country { Iso = "BO", Name = "BOLIVIA", PrintableName = "Bolivia", Iso3 = "BOL", CountryCode = 68 },
        new Country { Iso = "BA", Name = "BOSNIA AND HERZEGOVINA", PrintableName = "Bosnia and Herzegovina", Iso3 = "BIH", CountryCode = 70 },
        new Country { Iso = "BW", Name = "BOTSWANA", PrintableName = "Botswana", Iso3 = "BWA", CountryCode = 72 },
        new Country { Iso = "BV", Name = "BOUVET ISLAND", PrintableName = "Bouvet Island", Iso3 = null, CountryCode = null },
        new Country { Iso = "BR", Name = "BRAZIL", PrintableName = "Brazil", Iso3 = "BRA", CountryCode = 76 },
        new Country { Iso = "IO", Name = "BRITISH INDIAN OCEAN TERRITORY", PrintableName = "British Indian Ocean Territory", Iso3 = null, CountryCode = null },
        new Country { Iso = "BN", Name = "BRUNEI DARUSSALAM", PrintableName = "Brunei Darussalam", Iso3 = "BRN", CountryCode = 96 },
        new Country { Iso = "BG", Name = "BULGARIA", PrintableName = "Bulgaria", Iso3 = "BGR", CountryCode = 100 },
        new Country { Iso = "BF", Name = "BURKINA FASO", PrintableName = "Burkina Faso", Iso3 = "BFA", CountryCode = 854 },
        new Country { Iso = "BI", Name = "BURUNDI", PrintableName = "Burundi", Iso3 = "BDI", CountryCode = 108 },
        new Country { Iso = "KH", Name = "CAMBODIA", PrintableName = "Cambodia", Iso3 = "KHM", CountryCode = 116 },
        new Country { Iso = "CM", Name = "CAMEROON", PrintableName = "Cameroon", Iso3 = "CMR", CountryCode = 120 },
        new Country { Iso = "CA", Name = "CANADA", PrintableName = "Canada", Iso3 = "CAN", CountryCode = 124 },
        new Country { Iso = "CV", Name = "CAPE VERDE", PrintableName = "Cape Verde", Iso3 = "CPV", CountryCode = 132 },
        new Country { Iso = "KY", Name = "CAYMAN ISLANDS", PrintableName = "Cayman Islands", Iso3 = "CYM", CountryCode = 136 },
        new Country { Iso = "CF", Name = "CENTRAL AFRICAN REPUBLIC", PrintableName = "Central African Republic", Iso3 = "CAF", CountryCode = 140 },
        new Country { Iso = "TD", Name = "CHAD", PrintableName = "Chad", Iso3 = "TCD", CountryCode = 148 },
        new Country { Iso = "CL", Name = "CHILE", PrintableName = "Chile", Iso3 = "CHL", CountryCode = 152 },
        new Country { Iso = "CN", Name = "CHINA", PrintableName = "China", Iso3 = "CHN", CountryCode = 156 },
        new Country { Iso = "CX", Name = "CHRISTMAS ISLAND", PrintableName = "Christmas Island", Iso3 = null, CountryCode = null },
        new Country { Iso = "CC", Name = "COCOS (KEELING) ISLANDS", PrintableName = "Cocos (Keeling) Islands", Iso3 = null, CountryCode = null },
        new Country { Iso = "CO", Name = "COLOMBIA", PrintableName = "Colombia", Iso3 = "COL", CountryCode = 170 },
        new Country { Iso = "KM", Name = "COMOROS", PrintableName = "Comoros", Iso3 = "COM", CountryCode = 174 },
        new Country { Iso = "CG", Name = "CONGO", PrintableName = "Congo", Iso3 = "COG", CountryCode = 178 },
        new Country { Iso = "CD", Name = "CONGO, THE DEMOCRATIC REPUBLIC OF THE", PrintableName = "Congo, the Democratic Republic of the", Iso3 = "COD", CountryCode = 180 },
        new Country { Iso = "CK", Name = "COOK ISLANDS", PrintableName = "Cook Islands", Iso3 = "COK", CountryCode = 184 },
        new Country { Iso = "CR", Name = "COSTA RICA", PrintableName = "Costa Rica", Iso3 = "CRI", CountryCode = 188 },
        new Country { Iso = "CI", Name = "COTE D'IVOIRE", PrintableName = "Cote D'Ivoire", Iso3 = "CIV", CountryCode = 384 },
        new Country { Iso = "HR", Name = "CROATIA", PrintableName = "Croatia", Iso3 = "HRV", CountryCode = 191 },
        new Country { Iso = "CU", Name = "CUBA", PrintableName = "Cuba", Iso3 = "CUB", CountryCode = 192 },
        new Country { Iso = "CY", Name = "CYPRUS", PrintableName = "Cyprus", Iso3 = "CYP", CountryCode = 196 },
        new Country { Iso = "CZ", Name = "CZECH REPUBLIC", PrintableName = "Czech Republic", Iso3 = "CZE", CountryCode = 203 },
        new Country { Iso = "DK", Name = "DENMARK", PrintableName = "Denmark", Iso3 = "DNK", CountryCode = 208 },
        new Country { Iso = "DJ", Name = "DJIBOUTI", PrintableName = "Djibouti", Iso3 = "DJI", CountryCode = 262 },
        new Country { Iso = "DM", Name = "DOMINICA", PrintableName = "Dominica", Iso3 = "DMA", CountryCode = 212 },
        new Country { Iso = "DO", Name = "DOMINICAN REPUBLIC", PrintableName = "Dominican Republic", Iso3 = "DOM", CountryCode = 214 },
        new Country { Iso = "EC", Name = "ECUADOR", PrintableName = "Ecuador", Iso3 = "ECU", CountryCode = 218 },
        new Country { Iso = "EG", Name = "EGYPT", PrintableName = "Egypt", Iso3 = "EGY", CountryCode = 818 },
        new Country { Iso = "SV", Name = "EL SALVADOR", PrintableName = "El Salvador", Iso3 = "SLV", CountryCode = 222 },
        new Country { Iso = "GQ", Name = "EQUATORIAL GUINEA", PrintableName = "Equatorial Guinea", Iso3 = "GNQ", CountryCode = 226 },
        new Country { Iso = "ER", Name = "ERITREA", PrintableName = "Eritrea", Iso3 = "ERI", CountryCode = 232 },
        new Country { Iso = "EE", Name = "ESTONIA", PrintableName = "Estonia", Iso3 = "EST", CountryCode = 233 },
        new Country { Iso = "ET", Name = "ETHIOPIA", PrintableName = "Ethiopia", Iso3 = "ETH", CountryCode = 231 },
        new Country { Iso = "FK", Name = "FALKLAND ISLANDS (MALVINAS)", PrintableName = "Falkland Islands (Malvinas)", Iso3 = "FLK", CountryCode = 238 },
        new Country { Iso = "FO", Name = "FAROE ISLANDS", PrintableName = "Faroe Islands", Iso3 = "FRO", CountryCode = 234 },
        new Country { Iso = "FJ", Name = "FIJI", PrintableName = "Fiji", Iso3 = "FJI", CountryCode = 242 },
        new Country { Iso = "FI", Name = "FINLAND", PrintableName = "Finland", Iso3 = "FIN", CountryCode = 246 },
        new Country { Iso = "FR", Name = "FRANCE", PrintableName = "France", Iso3 = "FRA", CountryCode = 250 },
        new Country { Iso = "GF", Name = "FRENCH GUIANA", PrintableName = "French Guiana", Iso3 = "GUF", CountryCode = 254 },
        new Country { Iso = "PF", Name = "FRENCH POLYNESIA", PrintableName = "French Polynesia", Iso3 = "PYF", CountryCode = 258 },
        new Country { Iso = "TF", Name = "FRENCH SOUTHERN TERRITORIES", PrintableName = "French Southern Territories", Iso3 = null, CountryCode = null },
        new Country { Iso = "GA", Name = "GABON", PrintableName = "Gabon", Iso3 = "GAB", CountryCode = 266 },
        new Country { Iso = "GM", Name = "GAMBIA", PrintableName = "Gambia", Iso3 = "GMB", CountryCode = 270 },
        new Country { Iso = "GE", Name = "GEORGIA", PrintableName = "Georgia", Iso3 = "GEO", CountryCode = 268 },
        new Country { Iso = "DE", Name = "GERMANY", PrintableName = "Germany", Iso3 = "DEU", CountryCode = 276 },
        new Country { Iso = "GH", Name = "GHANA", PrintableName = "Ghana", Iso3 = "GHA", CountryCode = 288 },
        new Country { Iso = "GI", Name = "GIBRALTAR", PrintableName = "Gibraltar", Iso3 = "GIB", CountryCode = 292 },
        new Country { Iso = "GR", Name = "GREECE", PrintableName = "Greece", Iso3 = "GRC", CountryCode = 300 },
        new Country { Iso = "GL", Name = "GREENLAND", PrintableName = "Greenland", Iso3 = "GRL", CountryCode = 304 },
        new Country { Iso = "GD", Name = "GRENADA", PrintableName = "Grenada", Iso3 = "GRD", CountryCode = 308 },
        new Country { Iso = "GP", Name = "GUADELOUPE", PrintableName = "Guadeloupe", Iso3 = "GLP", CountryCode = 312 },
        new Country { Iso = "GU", Name = "GUAM", PrintableName = "Guam", Iso3 = "GUM", CountryCode = 316 },
        new Country { Iso = "GT", Name = "GUATEMALA", PrintableName = "Guatemala", Iso3 = "GTM", CountryCode = 320 },
        new Country { Iso = "GN", Name = "GUINEA", PrintableName = "Guinea", Iso3 = "GIN", CountryCode = 324 },
        new Country { Iso = "GW", Name = "GUINEA-BISSAU", PrintableName = "Guinea-Bissau", Iso3 = "GNB", CountryCode = 624 },
        new Country { Iso = "GY", Name = "GUYANA", PrintableName = "Guyana", Iso3 = "GUY", CountryCode = 328 },
        new Country { Iso = "HT", Name = "HAITI", PrintableName = "Haiti", Iso3 = "HTI", CountryCode = 332 },
        new Country { Iso = "HM", Name = "HEARD ISLAND AND MCDONALD ISLANDS", PrintableName = "Heard Island and Mcdonald Islands", Iso3 = null, CountryCode = null },
        new Country { Iso = "VA", Name = "HOLY SEE (VATICAN CITY STATE)", PrintableName = "Holy See (Vatican City State)", Iso3 = "VAT", CountryCode = 336 },
        new Country { Iso = "HN", Name = "HONDURAS", PrintableName = "Honduras", Iso3 = "HND", CountryCode = 340 },
        new Country { Iso = "HK", Name = "HONG KONG", PrintableName = "Hong Kong", Iso3 = "HKG", CountryCode = 344 },
        new Country { Iso = "HU", Name = "HUNGARY", PrintableName = "Hungary", Iso3 = "HUN", CountryCode = 348 },
        new Country { Iso = "IS", Name = "ICELAND", PrintableName = "Iceland", Iso3 = "ISL", CountryCode = 352 },
        new Country { Iso = "IN", Name = "INDIA", PrintableName = "India", Iso3 = "IND", CountryCode = 356 },
        new Country { Iso = "ID", Name = "INDONESIA", PrintableName = "Indonesia", Iso3 = "IDN", CountryCode = 360 },
        new Country { Iso = "IR", Name = "IRAN, ISLAMIC REPUBLIC OF", PrintableName = "Iran, Islamic Republic of", Iso3 = "IRN", CountryCode = 364 },
        new Country { Iso = "IQ", Name = "IRAQ", PrintableName = "Iraq", Iso3 = "IRQ", CountryCode = 368 },
        new Country { Iso = "IE", Name = "IRELAND", PrintableName = "Ireland", Iso3 = "IRL", CountryCode = 372 },
        new Country { Iso = "IL", Name = "ISRAEL", PrintableName = "Israel", Iso3 = "ISR", CountryCode = 376 },
        new Country { Iso = "IT", Name = "ITALY", PrintableName = "Italy", Iso3 = "ITA", CountryCode = 380 },
        new Country { Iso = "JM", Name = "JAMAICA", PrintableName = "Jamaica", Iso3 = "JAM", CountryCode = 388 },
        new Country { Iso = "JP", Name = "JAPAN", PrintableName = "Japan", Iso3 = "JPN", CountryCode = 392 },
        new Country { Iso = "JO", Name = "JORDAN", PrintableName = "Jordan", Iso3 = "JOR", CountryCode = 400 },
        new Country { Iso = "KZ", Name = "KAZAKHSTAN", PrintableName = "Kazakhstan", Iso3 = "KAZ", CountryCode = 398 },
        new Country { Iso = "KE", Name = "KENYA", PrintableName = "Kenya", Iso3 = "KEN", CountryCode = 404 },
        new Country { Iso = "KI", Name = "KIRIBATI", PrintableName = "Kiribati", Iso3 = "KIR", CountryCode = 296 },
        new Country { Iso = "KP", Name = "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", PrintableName = "Korea, Democratic People's Republic of", Iso3 = "PRK", CountryCode = 408 },
        new Country { Iso = "KR", Name = "KOREA, REPUBLIC OF", PrintableName = "Korea, Republic of", Iso3 = "KOR", CountryCode = 410 },
        new Country { Iso = "KW", Name = "KUWAIT", PrintableName = "Kuwait", Iso3 = "KWT", CountryCode = 414 },
        new Country { Iso = "KG", Name = "KYRGYZSTAN", PrintableName = "Kyrgyzstan", Iso3 = "KGZ", CountryCode = 417 },
        new Country { Iso = "LA", Name = "LAO PEOPLE'S DEMOCRATIC REPUBLIC", PrintableName = "Lao People's Democratic Republic", Iso3 = "LAO", CountryCode = 418 },
        new Country { Iso = "LV", Name = "LATVIA", PrintableName = "Latvia", Iso3 = "LVA", CountryCode = 428 },
        new Country { Iso = "LB", Name = "LEBANON", PrintableName = "Lebanon", Iso3 = "LBN", CountryCode = 422 },
        new Country { Iso = "LS", Name = "LESOTHO", PrintableName = "Lesotho", Iso3 = "LSO", CountryCode = 426 },
        new Country { Iso = "LR", Name = "LIBERIA", PrintableName = "Liberia", Iso3 = "LBR", CountryCode = 430 },
        new Country { Iso = "LY", Name = "LIBYAN ARAB JAMAHIRIYA", PrintableName = "Libyan Arab Jamahiriya", Iso3 = "LBY", CountryCode = 434 },
        new Country { Iso = "LI", Name = "LIECHTENSTEIN", PrintableName = "Liechtenstein", Iso3 = "LIE", CountryCode = 438 },
        new Country { Iso = "LT", Name = "LITHUANIA", PrintableName = "Lithuania", Iso3 = "LTU", CountryCode = 440 },
        new Country { Iso = "LU", Name = "LUXEMBOURG", PrintableName = "Luxembourg", Iso3 = "LUX", CountryCode = 442 },
        new Country { Iso = "MO", Name = "MACAO", PrintableName = "Macao", Iso3 = "MAC", CountryCode = 446 },
        new Country { Iso = "MK", Name = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", PrintableName = "Macedonia, the Former Yugoslav Republic of", Iso3 = "MKD", CountryCode = 807 },
        new Country { Iso = "MG", Name = "MADAGASCAR", PrintableName = "Madagascar", Iso3 = "MDG", CountryCode = 450 },
        new Country { Iso = "MW", Name = "MALAWI", PrintableName = "Malawi", Iso3 = "MWI", CountryCode = 454 },
        new Country { Iso = "MY", Name = "MALAYSIA", PrintableName = "Malaysia", Iso3 = "MYS", CountryCode = 458 },
        new Country { Iso = "MV", Name = "MALDIVES", PrintableName = "Maldives", Iso3 = "MDV", CountryCode = 462 },
        new Country { Iso = "ML", Name = "MALI", PrintableName = "Mali", Iso3 = "MLI", CountryCode = 466 },
        new Country { Iso = "MT", Name = "MALTA", PrintableName = "Malta", Iso3 = "MLT", CountryCode = 470 },
        new Country { Iso = "MH", Name = "MARSHALL ISLANDS", PrintableName = "Marshall Islands", Iso3 = "MHL", CountryCode = 584 },
        new Country { Iso = "MQ", Name = "MARTINIQUE", PrintableName = "Martinique", Iso3 = "MTQ", CountryCode = 474 },
        new Country { Iso = "MR", Name = "MAURITANIA", PrintableName = "Mauritania", Iso3 = "MRT", CountryCode = 478 },
        new Country { Iso = "MU", Name = "MAURITIUS", PrintableName = "Mauritius", Iso3 = "MUS", CountryCode = 480 },
        new Country { Iso = "YT", Name = "MAYOTTE", PrintableName = "Mayotte", Iso3 = null, CountryCode = null },
        new Country { Iso = "MX", Name = "MEXICO", PrintableName = "Mexico", Iso3 = "MEX", CountryCode = 484 },
        new Country { Iso = "FM", Name = "MICRONESIA, FEDERATED STATES OF", PrintableName = "Micronesia, Federated States of", Iso3 = "FSM", CountryCode = 583 },
        new Country { Iso = "MD", Name = "MOLDOVA, REPUBLIC OF", PrintableName = "Moldova, Republic of", Iso3 = "MDA", CountryCode = 498 },
        new Country { Iso = "MC", Name = "MONACO", PrintableName = "Monaco", Iso3 = "MCO", CountryCode = 492 },
        new Country { Iso = "MN", Name = "MONGOLIA", PrintableName = "Mongolia", Iso3 = "MNG", CountryCode = 496 },
        new Country { Iso = "MS", Name = "MONTSERRAT", PrintableName = "Montserrat", Iso3 = "MSR", CountryCode = 500 },
        new Country { Iso = "MA", Name = "MOROCCO", PrintableName = "Morocco", Iso3 = "MAR", CountryCode = 504 },
        new Country { Iso = "MZ", Name = "MOZAMBIQUE", PrintableName = "Mozambique", Iso3 = "MOZ", CountryCode = 508 },
        new Country { Iso = "MM", Name = "MYANMAR", PrintableName = "Myanmar", Iso3 = "MMR", CountryCode = 104 },
        new Country { Iso = "NA", Name = "NAMIBIA", PrintableName = "Namibia", Iso3 = "NAM", CountryCode = 516 },
        new Country { Iso = "NR", Name = "NAURU", PrintableName = "Nauru", Iso3 = "NRU", CountryCode = 520 },
        new Country { Iso = "NP", Name = "NEPAL", PrintableName = "Nepal", Iso3 = "NPL", CountryCode = 524 },
        new Country { Iso = "NL", Name = "NETHERLANDS", PrintableName = "Netherlands", Iso3 = "NLD", CountryCode = 528 },
        new Country { Iso = "AN", Name = "NETHERLANDS ANTILLES", PrintableName = "Netherlands Antilles", Iso3 = "ANT", CountryCode = 530 },
        new Country { Iso = "NC", Name = "NEW CALEDONIA", PrintableName = "New Caledonia", Iso3 = "NCL", CountryCode = 540 },
        new Country { Iso = "NZ", Name = "NEW ZEALAND", PrintableName = "New Zealand", Iso3 = "NZL", CountryCode = 554 },
        new Country { Iso = "NI", Name = "NICARAGUA", PrintableName = "Nicaragua", Iso3 = "NIC", CountryCode = 558 },
        new Country { Iso = "NE", Name = "NIGER", PrintableName = "Niger", Iso3 = "NER", CountryCode = 562 },
        new Country { Iso = "NG", Name = "NIGERIA", PrintableName = "Nigeria", Iso3 = "NGA", CountryCode = 566 },
        new Country { Iso = "NU", Name = "NIUE", PrintableName = "Niue", Iso3 = "NIU", CountryCode = 570 },
        new Country { Iso = "NF", Name = "NORFOLK ISLAND", PrintableName = "Norfolk Island", Iso3 = "NFK", CountryCode = 574 },
        new Country { Iso = "MP", Name = "NORTHERN MARIANA ISLANDS", PrintableName = "Northern Mariana Islands", Iso3 = "MNP", CountryCode = 580 },
        new Country { Iso = "NO", Name = "NORWAY", PrintableName = "Norway", Iso3 = "NOR", CountryCode = 578 },
        new Country { Iso = "OM", Name = "OMAN", PrintableName = "Oman", Iso3 = "OMN", CountryCode = 512 },
        new Country { Iso = "PK", Name = "PAKISTAN", PrintableName = "Pakistan", Iso3 = "PAK", CountryCode = 586 },
        new Country { Iso = "PW", Name = "PALAU", PrintableName = "Palau", Iso3 = "PLW", CountryCode = 585 },
        new Country { Iso = "PS", Name = "PALESTINIAN TERRITORY, OCCUPIED", PrintableName = "Palestinian Territory, Occupied", Iso3 = null, CountryCode = null },
        new Country { Iso = "PA", Name = "PANAMA", PrintableName = "Panama", Iso3 = "PAN", CountryCode = 591 },
        new Country { Iso = "PG", Name = "PAPUA NEW GUINEA", PrintableName = "Papua New Guinea", Iso3 = "PNG", CountryCode = 598 },
        new Country { Iso = "PY", Name = "PARAGUAY", PrintableName = "Paraguay", Iso3 = "PRY", CountryCode = 600 },
        new Country { Iso = "PE", Name = "PERU", PrintableName = "Peru", Iso3 = "PER", CountryCode = 604 },
        new Country { Iso = "PH", Name = "PHILIPPINES", PrintableName = "Philippines", Iso3 = "PHL", CountryCode = 608 },
        new Country { Iso = "PN", Name = "PITCAIRN", PrintableName = "Pitcairn", Iso3 = "PCN", CountryCode = 612 },
        new Country { Iso = "PL", Name = "POLAND", PrintableName = "Poland", Iso3 = "POL", CountryCode = 616 },
        new Country { Iso = "PT", Name = "PORTUGAL", PrintableName = "Portugal", Iso3 = "PRT", CountryCode = 620 },
        new Country { Iso = "PR", Name = "PUERTO RICO", PrintableName = "Puerto Rico", Iso3 = "PRI", CountryCode = 630 },
        new Country { Iso = "QA", Name = "QATAR", PrintableName = "Qatar", Iso3 = "QAT", CountryCode = 634 },
        new Country { Iso = "RE", Name = "REUNION", PrintableName = "Reunion", Iso3 = "REU", CountryCode = 638 },
        new Country { Iso = "RO", Name = "ROMANIA", PrintableName = "Romania", Iso3 = "ROM", CountryCode = 642 },
        new Country { Iso = "RU", Name = "RUSSIAN FEDERATION", PrintableName = "Russian Federation", Iso3 = "RUS", CountryCode = 643 },
        new Country { Iso = "RW", Name = "RWANDA", PrintableName = "Rwanda", Iso3 = "RWA", CountryCode = 646 },
        new Country { Iso = "SH", Name = "SAINT HELENA", PrintableName = "Saint Helena", Iso3 = "SHN", CountryCode = 654 },
        new Country { Iso = "KN", Name = "SAINT KITTS AND NEVIS", PrintableName = "Saint Kitts and Nevis", Iso3 = "KNA", CountryCode = 659 },
        new Country { Iso = "LC", Name = "SAINT LUCIA", PrintableName = "Saint Lucia", Iso3 = "LCA", CountryCode = 662 },
        new Country { Iso = "PM", Name = "SAINT PIERRE AND MIQUELON", PrintableName = "Saint Pierre and Miquelon", Iso3 = "SPM", CountryCode = 666 },
        new Country { Iso = "VC", Name = "SAINT VINCENT AND THE GRENADINES", PrintableName = "Saint Vincent and the Grenadines", Iso3 = "VCT", CountryCode = 670 },
        new Country { Iso = "WS", Name = "SAMOA", PrintableName = "Samoa", Iso3 = "WSM", CountryCode = 882 },
        new Country { Iso = "SM", Name = "SAN MARINO", PrintableName = "San Marino", Iso3 = "SMR", CountryCode = 674 },
        new Country { Iso = "ST", Name = "SAO TOME AND PRINCIPE", PrintableName = "Sao Tome and Principe", Iso3 = "STP", CountryCode = 678 },
        new Country { Iso = "SA", Name = "SAUDI ARABIA", PrintableName = "Saudi Arabia", Iso3 = "SAU", CountryCode = 682 },
        new Country { Iso = "SN", Name = "SENEGAL", PrintableName = "Senegal", Iso3 = "SEN", CountryCode = 686 },
        new Country { Iso = "CS", Name = "SERBIA AND MONTENEGRO", PrintableName = "Serbia and Montenegro", Iso3 = null, CountryCode = null },
        new Country { Iso = "SC", Name = "SEYCHELLES", PrintableName = "Seychelles", Iso3 = "SYC", CountryCode = 690 },
        new Country { Iso = "SL", Name = "SIERRA LEONE", PrintableName = "Sierra Leone", Iso3 = "SLE", CountryCode = 694 },
        new Country { Iso = "SG", Name = "SINGAPORE", PrintableName = "Singapore", Iso3 = "SGP", CountryCode = 702 },
        new Country { Iso = "SK", Name = "SLOVAKIA", PrintableName = "Slovakia", Iso3 = "SVK", CountryCode = 703 },
        new Country { Iso = "SI", Name = "SLOVENIA", PrintableName = "Slovenia", Iso3 = "SVN", CountryCode = 705 },
        new Country { Iso = "SB", Name = "SOLOMON ISLANDS", PrintableName = "Solomon Islands", Iso3 = "SLB", CountryCode = 90 },
        new Country { Iso = "SO", Name = "SOMALIA", PrintableName = "Somalia", Iso3 = "SOM", CountryCode = 706 },
        new Country { Iso = "ZA", Name = "SOUTH AFRICA", PrintableName = "South Africa", Iso3 = "ZAF", CountryCode = 710 },
        new Country { Iso = "GS", Name = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", PrintableName = "South Georgia and the South Sandwich Islands", Iso3 = null, CountryCode = null },
        new Country { Iso = "ES", Name = "SPAIN", PrintableName = "Spain", Iso3 = "ESP", CountryCode = 724 },
        new Country { Iso = "LK", Name = "SRI LANKA", PrintableName = "Sri Lanka", Iso3 = "LKA", CountryCode = 144 },
        new Country { Iso = "SD", Name = "SUDAN", PrintableName = "Sudan", Iso3 = "SDN", CountryCode = 736 },
        new Country { Iso = "SR", Name = "SURINAME", PrintableName = "Suriname", Iso3 = "SUR", CountryCode = 740 },
        new Country { Iso = "SJ", Name = "SVALBARD AND JAN MAYEN", PrintableName = "Svalbard and Jan Mayen", Iso3 = "SJM", CountryCode = 744 },
        new Country { Iso = "SZ", Name = "SWAZILAND", PrintableName = "Swaziland", Iso3 = "SWZ", CountryCode = 748 },
        new Country { Iso = "SE", Name = "SWEDEN", PrintableName = "Sweden", Iso3 = "SWE", CountryCode = 752 },
        new Country { Iso = "CH", Name = "SWITZERLAND", PrintableName = "Switzerland", Iso3 = "CHE", CountryCode = 756 },
        new Country { Iso = "SY", Name = "SYRIAN ARAB REPUBLIC", PrintableName = "Syrian Arab Republic", Iso3 = "SYR", CountryCode = 760 },
        new Country { Iso = "TW", Name = "TAIWAN, PROVINCE OF CHINA", PrintableName = "Taiwan, Province of China", Iso3 = "TWN", CountryCode = 158 },
        new Country { Iso = "TJ", Name = "TAJIKISTAN", PrintableName = "Tajikistan", Iso3 = "TJK", CountryCode = 762 },
        new Country { Iso = "TZ", Name = "TANZANIA, UNITED REPUBLIC OF", PrintableName = "Tanzania, United Republic of", Iso3 = "TZA", CountryCode = 834 },
        new Country { Iso = "TH", Name = "THAILAND", PrintableName = "Thailand", Iso3 = "THA", CountryCode = 764 },
        new Country { Iso = "TL", Name = "TIMOR-LESTE", PrintableName = "Timor-Leste", Iso3 = null, CountryCode = null },
        new Country { Iso = "TG", Name = "TOGO", PrintableName = "Togo", Iso3 = "TGO", CountryCode = 768 },
        new Country { Iso = "TK", Name = "TOKELAU", PrintableName = "Tokelau", Iso3 = "TKL", CountryCode = 772 },
        new Country { Iso = "TO", Name = "TONGA", PrintableName = "Tonga", Iso3 = "TON", CountryCode = 776 },
        new Country { Iso = "TT", Name = "TRINIDAD AND TOBAGO", PrintableName = "Trinidad and Tobago", Iso3 = "TTO", CountryCode = 780 },
        new Country { Iso = "TN", Name = "TUNISIA", PrintableName = "Tunisia", Iso3 = "TUN", CountryCode = 788 },
        new Country { Iso = "TR", Name = "TURKEY", PrintableName = "Turkey", Iso3 = "TUR", CountryCode = 792 },
        new Country { Iso = "TM", Name = "TURKMENISTAN", PrintableName = "Turkmenistan", Iso3 = "TKM", CountryCode = 795 },
        new Country { Iso = "TC", Name = "TURKS AND CAICOS ISLANDS", PrintableName = "Turks and Caicos Islands", Iso3 = "TCA", CountryCode = 796 },
        new Country { Iso = "TV", Name = "TUVALU", PrintableName = "Tuvalu", Iso3 = "TUV", CountryCode = 798 },
        new Country { Iso = "UG", Name = "UGANDA", PrintableName = "Uganda", Iso3 = "UGA", CountryCode = 800 },
        new Country { Iso = "UA", Name = "UKRAINE", PrintableName = "Ukraine", Iso3 = "UKR", CountryCode = 804 },
        new Country { Iso = "AE", Name = "UNITED ARAB EMIRATES", PrintableName = "United Arab Emirates", Iso3 = "ARE", CountryCode = 784 },
        new Country { Iso = "GB", Name = "UNITED KINGDOM", PrintableName = "United Kingdom", Iso3 = "GBR", CountryCode = 826 },
        new Country { Iso = "US", Name = "UNITED STATES", PrintableName = "United States", Iso3 = "USA", CountryCode = 840 },
        new Country { Iso = "UM", Name = "UNITED STATES MINOR OUTLYING ISLANDS", PrintableName = "United States Minor Outlying Islands", Iso3 = null, CountryCode = null },
        new Country { Iso = "UY", Name = "URUGUAY", PrintableName = "Uruguay", Iso3 = "URY", CountryCode = 858 },
        new Country { Iso = "UZ", Name = "UZBEKISTAN", PrintableName = "Uzbekistan", Iso3 = "UZB", CountryCode = 860 },
        new Country { Iso = "VU", Name = "VANUATU", PrintableName = "Vanuatu", Iso3 = "VUT", CountryCode = 548 },
        new Country { Iso = "VE", Name = "VENEZUELA", PrintableName = "Venezuela", Iso3 = "VEN", CountryCode = 862 },
        new Country { Iso = "VN", Name = "VIET NAM", PrintableName = "Viet Nam", Iso3 = "VNM", CountryCode = 704 },
        new Country { Iso = "VG", Name = "VIRGIN ISLANDS, BRITISH", PrintableName = "Virgin Islands, British", Iso3 = "VGB", CountryCode = 92 },
        new Country { Iso = "VI", Name = "VIRGIN ISLANDS, U.S.", PrintableName = "Virgin Islands, U.s.", Iso3 = "VIR", CountryCode = 850 },
        new Country { Iso = "WF", Name = "WALLIS AND FUTUNA", PrintableName = "Wallis and Futuna", Iso3 = "WLF", CountryCode = 876 },
        new Country { Iso = "EH", Name = "WESTERN SAHARA", PrintableName = "Western Sahara", Iso3 = "ESH", CountryCode = 732 },
        new Country { Iso = "YE", Name = "YEMEN", PrintableName = "Yemen", Iso3 = "YEM", CountryCode = 887 },
        new Country { Iso = "ZM", Name = "ZAMBIA", PrintableName = "Zambia", Iso3 = "ZMB", CountryCode = 894 },
        new Country { Iso = "ZW", Name = "ZIMBABWE", PrintableName = "Zimbabwe", Iso3 = "ZWE", CountryCode = 716 }
      };

      return countries;
    }

    private static State[] States()
{
      var states = new[]
        {
          new State { Name = "Alabama", Abbreviation = "AL" }, 
          new State { Name = "Alaska", Abbreviation = "AK" },
          new State { Name = "Arizona", Abbreviation = "AZ" },
          new State { Name = "Arkansas", Abbreviation = "AR" },
          new State { Name = "California", Abbreviation = "CA" },
          new State { Name = "Colorado", Abbreviation = "CO" },
          new State { Name = "Connecticut", Abbreviation = "CT" },
          new State { Name = "Delaware", Abbreviation = "DE" },
          new State { Name = "Florida", Abbreviation = "FL" },
          new State { Name = "Georgia", Abbreviation = "GA" },
          new State { Name = "Hawaii", Abbreviation = "HI" },
          new State { Name = "Idaho", Abbreviation = "ID" },
          new State { Name = "Illinois", Abbreviation = "IL" },
          new State { Name = "Indiana", Abbreviation = "IN" },
          new State { Name = "Iowa", Abbreviation = "IA" },
          new State { Name = "Kansas", Abbreviation = "KS" },
          new State { Name = "Kentucky", Abbreviation = "KY" },
          new State { Name = "Louisiana", Abbreviation = "LA" },
          new State { Name = "Maine", Abbreviation = "ME" },
          new State { Name = "Maryland", Abbreviation = "MD" },
          new State { Name = "Massachusetts", Abbreviation = "MA" },
          new State { Name = "Michigan", Abbreviation = "MI" },
          new State { Name = "Minnesota", Abbreviation = "MN" },
          new State { Name = "Mississippi", Abbreviation = "MS" },
          new State { Name = "Missouri", Abbreviation = "MO" },
          new State { Name = "Montana", Abbreviation = "MT" },
          new State { Name = "Nebraska", Abbreviation = "NE" },
          new State { Name = "Nevada", Abbreviation = "NV" },
          new State { Name = "New Hampshire", Abbreviation = "NH" },
          new State { Name = "New Jersey", Abbreviation = "NJ" },
          new State { Name = "New Mexico", Abbreviation = "NM" },
          new State { Name = "New York", Abbreviation = "NY" },
          new State { Name = "North Carolina", Abbreviation = "NC" },
          new State { Name = "North Dakota", Abbreviation = "ND" },
          new State { Name = "Ohio", Abbreviation = "OH" },
          new State { Name = "Oklahoma", Abbreviation = "OK" },
          new State { Name = "Oregon", Abbreviation = "OR" },
          new State { Name = "Pennsylvania", Abbreviation = "PA" },
          new State { Name = "Rhode Island", Abbreviation = "RI" },
          new State { Name = "South Carolina", Abbreviation = "SC" },
          new State { Name = "South Dakota", Abbreviation = "SD" },
          new State { Name = "Tennessee", Abbreviation = "TN" },
          new State { Name = "Texas", Abbreviation = "TX" },
          new State { Name = "Utah", Abbreviation = "UT" },
          new State { Name = "Vermont", Abbreviation = "VT" },
          new State { Name = "Virginia", Abbreviation = "VA" },
          new State { Name = "Washington", Abbreviation = "WA" },
          new State { Name = "West Virginia", Abbreviation = "WV" },
          new State { Name = "Wisconsin", Abbreviation = "WI" },
          new State { Name = "Wyoming", Abbreviation = "WY" },
          new State { Name = "Washington DC", Abbreviation = "DC" }
        };
      return states;
    }
  }
}
